### PR TITLE
Massinve Inserts

### PR DESCRIPTION
**Pull request by tomibolo**
This is a fast solution:
- It doesn't make massive updates, only makes massive inserts in the most performance way, using transactions and without iterations.

- Validates data using Laravel Validation Requests(https://laravel.com/docs/5.7/validation#creating-form-requests)

### CODE REVIEW

**Comment by orbitrod** [comment]
Wow this is awesome.

I see that authorizes the user.  How does that work?  Do I have to pass a token or something for it to authenticate?

What is the format of the JSON that I need to POST to /sensors/createMany?

**Comment by tomibolo** [comment]
No authorization is needed. At least i didnt configure it.

I copied the json that was on the README so you could with it.

**Comment by orbitrod** [comment]
I tried it and it works except for the timestamps.  Go to this URL and you will see the records with the code before that have timestamps and the records with your code without timestamps.

https://iot.enoch.systems/sensors/public/api/sensors?page=181

**Comment by orbitrod** [comment]
For the future, how would authorization work?  Right now the app is sitting out in the open and anyone can send an API request.

**Comment by tomibolo** [comment]
Well. It depends wich type authorization you may need. Laravel counts with a package that gives you a compelete solution for auth. https://laravel.com/docs/5.7/passport

Its really simple to configurate.

We can dig about what you need and after that look for the best solution.

About the timestamps its really simple to add them. Im out of my house right now. Im gonna be back in about 2 hours and create a PR wich changes.

**Comment by orbitrod** [comment]
For now, could you implement some kind of shared secret key, that can be used to authenticate the user?

**Pull request merged**
